name: cicd spring angular

on:
  push:
    branches: seance2

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        -  name: checkout code source 
           uses: actions/checkout@v6

        - name: Build and test Spring boot
          run: |
            cd springboot/app
            chmod +x mvnw
            ./mvnw clean package
            ./mvnw clean verify 
        - name: Build and Push Backend Docker image 
          run: |
            docker build -t nouran10/spring-app .
            docker push nouran10/spring-app .